CREATE TABLE RIDE (
    id_ride BIGINT AUTO_INCREMENT PRIMARY KEY,
    ride_from VARCHAR(40) NOT NULL,
    ride_to VARCHAR(40) NOT NULL,
    ride_date DATETIME,
    seats INT NOT NULL,
    id_owner BIGINT NOT NULL
);

CREATE TABLE USER (
    id_user BIGINT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(40) NOT NULL,
    surname VARCHAR(40) NOT NULL
);

CREATE TABLE BOOKED_RIDE (
    id_ride BIGINT NOT NULL,
    id_passenger BIGINT NOT NULL
);

ALTER TABLE RIDE
    ADD CONSTRAINT FK_RIDE_OWNER
        FOREIGN KEY (id_owner) REFERENCES USER(id_user);

ALTER TABLE BOOKED_RIDE
    ADD CONSTRAINT FK_BOOKED_RIDE
        FOREIGN KEY (id_passenger) REFERENCES USER(id_user);
